on:
  push:
    branches:
      - main
    tags:
      - "**"
  workflow_dispatch:
  pull_request:

name: CI

jobs:
  check:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-24.04, ubuntu-24.04-arm]
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
      - uses: cachix/cachix-action@v16
        with:
          name: newam
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - run: nix flake check -L
